### ISSUE TITLE
Memory

### ISSUE THREAD

**Issue by raaka1** [raaka1/samv01#12]
According to system monitor, we are using  710 MB on Jetson TX1,  but our app shows double.

**Comment by wardellsk** [comment]
this is an issue with psutil virtual_memory(). see:
https://github.com/giampaolo/psutil/issues/685

**Comment by MarioVilas** [comment]
I would guess it is probably easier to just parse the output of the 'free' command.

**Comment by MarioVilas** [comment]
I'm trying to understand this code:
`    mem = psutil.virtual_memory()
    mem_total = mem.total / 2 ** 30
    mem_used = round(mem.used / 2.0 ** 30.0, 2)
                  mem_total=mem_total)`
Why are the values being divided by two and then multiplied by 30? Is this a requirement of the graph widget or is it something to "fix" the bad values from psutil?

**Comment by wardellsk** [comment]
I did this to convert the byte value to GBs; I probably should have done something with the bitwise operator like `mem.total >> 30` or something else more pythonic.

I think I'm just going to get the output of the 'free' command for this issue though instead of using psutil.

**Comment by MarioVilas** [comment]
I have it partially implemented already, if you prefer I can try and finish
it.

On Thursday, 30 June 2016, Kyle Wardell <notifications@github.com> wrote:

> I did this to convert the byte value to GBs; I probably should have done
> something with the bitwise operator like mem.total >> 30 or something
> else more pythonic.
>
> I think I'm just going to get the output of the 'free' command for this
> issue though instead of using psutil.
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/raaka1/samv01/issues/12#issuecomment-229796315>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAN6Ux88DjhKJfxUuLREdWJMgXOCvZaTks5qRDcEgaJpZM4I7_tt>
> .
>


-- 
“There's a reason we separate military and the police: one fights the enemy
of the state, the other serves and protects the people. When the military
becomes both, then the enemies of the state tend to become the people.”

**Comment by wardellsk** [comment]
> I have it partially implemented already, if you prefer I can try and finish
it.

Sounds good to me. Thanks.

**Comment by MarioVilas** [comment]
Turns out parsing 'free' doesn't work either. I'm not sure why but the output of the free command reports a lot more memory than htop - I suppose it doesn't really give you the actual RAM usage values but the virtual memory sizes instead, which won't get us exactly what we want, since shared memory pages may get reported twice. But this is just speculation, I'll look into it a bit more.

**Comment by MarioVilas** [comment]
Ah, solved it. This page gave me the explanation on how the 'free' command output should be interpreted: http://www.linuxatemyram.com/

**Comment by raaka1** [comment]
Ravi Kiran.K
Office:+6598821443 <http://+6598821443>
Timezone:   GMT + 8:00
http://www.hackerstrip.com/ <http://www.hackerstrip.com/>
https://hackerstrip.exposure.co/ <https://hackerstrip.exposure.co/>
https://twitter.com/Hackerstrip <https://twitter.com/Hackerstrip>
http://hackerstrip.com/hackerstrip.asc <http://hackerstrip.com/hackerstrip.asc>
https://www.facebook.com/pages/Hackerstripcom/ <https://www.facebook.com/pages/Hackerstripcom/>
